version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: sinapsis-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sinapsis
      MYSQL_USER: sinapsis
      MYSQL_PASSWORD: sinapsis
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
